In [34]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [35]:
cd /content/drive/MyDrive

/content/drive/MyDrive

In [36]:
cd NLP_using_machine_learning/

/content/drive/MyDrive/NLP_using_machine_learning

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [38]:
df = pd.read_csv('train.txt',sep =";",header = None,names = ['text','emotion'])

In [39]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [40]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [41]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i+=1


df['emotion'] = df['emotion'].map(emotion_numbers)

In [42]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [43]:
df['text'] =df['text'].apply(lambda x: x.lower())

In [44]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [45]:
df['text'] = df['text'].apply(remove_punc)

In [46]:
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return  new

df['text'] = df['text'].apply(remove_numbers)

In [47]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new = new + i
  return  new

df['text'] = df['text'].apply(remove_emojis)

In [48]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [49]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [50]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [51]:
df['text'] = df['text'].apply(remove)

In [52]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [56]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [57]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [58]:
bow_vectorizer = CountVectorizer()

In [59]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [60]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [61]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 26934 stored elements and shape (3200, 13359)>

In [62]:
from sklearn.naive_bayes import MultinomialNB

In [64]:
from sklearn.metrics import accuracy_score

In [65]:
nb_model = MultinomialNB()

In [66]:
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [67]:
pred_nb = nb_model.predict(X_test_bow)

In [69]:
print(accuracy_score(y_test,pred_nb))

0.7678125

In [70]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [71]:
y_pred = nb2_model.predict(X_test_tfidf)

In [72]:
print(accuracy_score(y_test, y_pred))

0.6609375

In [73]:
from sklearn.linear_model import LogisticRegression

In [74]:
logistic_model = LogisticRegression(max_iter=1000)

In [75]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [76]:
log_pred = logistic_model.predict(X_test_tfidf)

In [77]:
print(accuracy_score(y_test,log_pred ))

0.8615625